language: node_js
node_js:
  - node

branches:
  only:
    - master

script:
  - npm run lint
  - npm run test

deploy:
  - provider: script
    script: bash scripts/deploy.sh production
    on:
      branch: master

notifications:
  email: false
