dist: bionic
language: node_js
node_js:
  - lts/*

addons:
  ssh_known_hosts: halley.uberspace.de

branches:
  only:
    - master

script:
  - yarn run lint
  - yarn run build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_9b935b919483_key -iv $encrypted_9b935b919483_iv -in christianost-travis.enc -out christianost-travis -d
  - chmod 400 christianost-travis

deploy:
  - provider: script
    skip_cleanup: true
    script: rsync --progress -r -e "ssh -i christianost-travis" public/* $deploy_user@$deploy_host:$deploy_path
    on:
      branch: master

notifications:
  email: false
