language: node_js
node_js:
  - node

cache: npm

addons:
  apt:
    packages:
      - sshpass

branches:
  only:
    - master

script:
  - npm run lint

before_deploy:
  - npm run build

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master

notifications:
  email: false
