language: node_js
node_js:
  - node

cache: npm

addons:
  apt:
    packages:
      - sshpass

branches:
  only:
    - master

env:
  global:
    - web_build_dir=dist/web/.
    - server_build_dir=dist/server/.

script:
  - npm run lint
  - npm run test

before_deploy:
  - npm run build

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master

notifications:
  email: false
