dist: bionic
language: node_js
node_js:
  - lts/*

cache: npm

branches:
  only:
    - master

script:
  - npm run lint
  - npm run build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_9b935b919483_key -iv $encrypted_9b935b919483_iv -in christianost-travis.enc -out christianost-travis -d
  - echo $deploy_host >> $HOME/.ssh/known_hosts

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master

notifications:
  email: false
